services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=devpass
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql  # ✅ bind mount

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=rootpass
    depends_on:
      - mysql

volumes: {}